name: SBCW
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9783669239841402
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.09178633382543921
  lightness: 0.09172030515037477
  saturation: 0.47222462948411703
  rhythmicContrast: 0.039050327613949776
purpose: []
